### ISSUE TITLE
Easier deployment of sample resources, metadata, and annotations

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/digital_slide_archive#245]
Currently, the provisioning script will install a fixed set of samples if requested.  It would be nice if this could be specified more explicitly.  Something like:
```
initial-data:
  - source-host: <girder api url>
    source-resource-path: </collection/sample/folder>
    destination-resource-path: </collection/sample/folder>
    destination-owner: <user id>
    include-metadata: <boolean>
    include-annotations: <boolean>
```
